name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [upgr1]

env:
  AWS_REGION: ca-central-1
  APPLICATION_NAME: cf-app
  ENVIRONMENT_NAME: cf-app-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Free disk space
        uses: EriksenCarl/free-disk-space-action@v1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          swift: true
          docker-images: false   # keep this false, you need Docker for EB packaging

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Check disk usage after cleanup
        run: df -h
        
      - name: Remove unused Docker images
        run: docker system prune -af

      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/aws-elasticbeanstalk-deploy@v1.0.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          application-name: ${{ env.APPLICATION_NAME }}
          environment-name: ${{ env.ENVIRONMENT_NAME }}
          solution-stack-name: '64bit Amazon Linux 2023 v4.12.0 running Docker'
          option-settings: |
            [
              {
                "Namespace": "aws:autoscaling:launchconfiguration",
                "OptionName": "IamInstanceProfile",
                "Value": "aws-elasticbeanstalk-ec2-role"
              },
              {
                "Namespace": "aws:elasticbeanstalk:environment",
                "OptionName": "ServiceRole",
                "Value": "aws-elasticbeanstalk-service-role"
              },
              {
                "Namespace": "aws:elasticbeanstalk:managedactions",
                "OptionName": "ManagedActionsEnabled",
                "Value": "true"
              },
              {
                "Namespace": "aws:elasticbeanstalk:managedactions:platformupdate",
                "OptionName": "UpdateLevel",
                "Value": "minor"
              }
            ]
