  name: shinyapps-publish
  on:
    push:
      branches: [dev]
  
  jobs:
    deploy: 
      name: Deploy to shinyappsio

      # allow skipping deployment for commits containing '[automated]' or '[no-deploy]' in the commit message
      if: "!contains(github.event.head_commit.message, '[automated]') && !contains(github.event.head_commit.message, '[no-deploy]')"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6
        - name: Build image
          run: >
            docker build -t cf-app .
            --build-arg HTTR_KEY=${{ secrets.SHINYAPPS_TOKEN }}
            --build-arg DB_PASS=${{ secrets.SHINYAPPS_TOKEN }}
            --build-arg DB_USER=${{ secrets.SHINYAPPS_TOKEN }}
            
        - name: Run container
          run: >
            docker run
            -e SHINYAPPS_ACCOUNT=${{ secrets.SHINYAPPS_TOKEN }}
            -e SHINYAPPS_TOKEN=${{ secrets.SHINYAPPS_TOKEN }}
            -e SHINYAPPS_SECRET=${{ secrets.SHINYAPPS_SECRET }}
            cf-app
            