  name: shinyapps-publish
  on:
    push:
      branches: [dev]
  
  jobs:
    deploy: 
      name: Deploy to shinyappsio

      # allow skipping deployment for commits containing '[automated]' or '[no-deploy]' in the commit message
      if: "!contains(github.event.head_commit.message, '[automated]') && !contains(github.event.head_commit.message, '[no-deploy]')"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6
        - name: Build image
          run: >
            docker build -t cf-app .
            --build-arg DB_NAME=${{ secrets.DB_NAME }}
            --build-arg DB_USER=${{ secrets.DB_USER }}
            --build-arg DB_HOST=${{ secrets.DB_HOST }}
            --build-arg DB_PASS=${{ secrets.DB_PASS }}
            --build-arg DB_PORT=${{ secrets.DB_PORT }}
            
        - name: Execute
          run: >
            docker run
            -e SHINYAPPS_ACCOUNT=${{ secrets.SHINYAPPS_ACCOUNT }}
            -e SHINYAPPS_TOKEN=${{ secrets.SHINYAPPS_TOKEN }}
            -e SHINYAPPS_SECRET=${{ secrets.SHINYAPPS_SECRET }}
            cf-app
            